# Generated by Django 3.0.6 on 2020-07-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
