# Generated by Django 2.2.5 on 2020-08-04 15:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200801_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=250, populate_from='title', unique_for_date='publish'),
        ),
    ]
